<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css">
<link rel="stylesheet" href="css/style.css">
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<script src="bower_components/bootstrap/dist/js/
bootstrap.js"></script>
<style media="screen">
  section{
    width: 100vw;
    height: 100vh;
  }
  .cl_white {
    color: white;
  }
  img {
    width: 300px;
    transition: opacity 1s ease-in-out;
  }
  img:hover {
    opacity: .5;
  }
</style>

  </head>
  <body data-spy="scroll" data-target=".navbar">
    <nav class ="navbar navbar-inverse navbar-fixed-bottom">
      <ul class="nav navbar-nav">
        <li><a href="index.php">Home</a></li>
        <li><a href="add-work.phtml">add Work</a></li>
      </ul>
    </nav>


    <div class="container">

<form action="add.php" method="post" enctype="multipart/form-data">
 <div class="form-group">
   <label for="name">title</label>
   <input type="text" class="form-control" name="name"  placeholder="intitulé du travail">
 </div>
 <div class="form-group">
   <label for="link">Link</label>
   <input type="text" class="form-control" name="link" placeholder="lien vers le travail">
 </div>
 <div class="form-group">
   <label for="inputFile">Envoyer votre image</label>
   <input type="file" name="inputFile">
 </div>
<div class="form-group">
   <label for="description">description</label>
   <textarea type="text" class="form-control" name="description" placeholder="Courte description"></textarea>
 </div>
 <button type="submit" class="btn btn-default">Submit</button>
</form>
    </div>
  </body>

</html>
