<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css">
<link rel="stylesheet" href="css/main.css">
<link rel="stylesheet" href="css/responsive.css">
<link rel="stylesheet" href="css/materialize.min.css">


<link rel="stylesheet" href="css/normalize.css">
<link rel="stylesheet" href="css/font-awesome.min.css">
<link rel="stylesheet" href="css/materialize.min.css" media="screen,projection">
<link rel="stylesheet" href="css/bootstrap.css" media="screen,projection">

<link rel="stylesheet" href="css/animate.min.css" media="screen,projection">
<link rel="stylesheet" href="css/sweet-alert.css" media="screen,projection">

<link rel="stylesheet" href="css/owl.carousel.css" media="screen,projection">
<link rel="stylesheet" href="css/owl.transitions.css" media="screen,projection">
<link rel="stylesheet" href="css/owl.theme.css" media="screen,projection">

<link rel="stylesheet" href="css/main.css">
<link rel="stylesheet" href="css/responsive.css">
<link rel="stylesheet" href="css/color1.css">
<link rel="stylesheet" href="css/custom.css">


<style media="screen">
  section{
    width: 100vw;
    height: 100vh;
  }
  .cl_white {
    color: white;
  }
  img {
    width: 300px;
    height: 200px;
    transition: opacity 1s ease-in-out;
  }
  img:hover {
    opacity: .5;
  }
</style>

  </head>
  <body data-spy="scroll" data-target=".navbar">
    <nav class ="navbar navbar-inverse navbar-fixed-bottom">
      <ul class="nav navbar-nav">
        <li><a href="#home">Home</a></li>
        <li><a href="#work">What i do</a></li>
        <li><a href="add-work.phtml">add Work</a></li>
      </ul>
    </nav>
    <section id="home"  style="background: url(images/header.jpg); background-size: 100% 100%;" class="cl_white text-center">
      <h1>My portofolio</h1>
      <p class="lead">
       Bienvenue dans mon univers!
      </p>
      <button class="btn btn-default"><a href="mailto:sergembotta@mailoo.org">Contacter moi</a></button>
    </section>

    <section id="work" class="container">
        <h1>My Work</h1>

      <div id="portfolioModal" class="modal white" style="display: none; top: 0px; opacity: 1;">
        <div class="model-img"><img style="width:60%" src="" alt="Portfolio Image"></div>
        <div class="modal-content">
          <h2 class="title"></h2>
          <p class="m-content"></p>
        </div>
        <div class="modal-footer">
          <a href="" target="_blank" class="waves-effect btn-flat brand-text modal-action">Plus d'informations</a>
          <a href="" class="waves-effect btn-flat brand-text modal-action modal-close">annuler</a>
        </div>
      </div>

      <div class="portfolio-bottom">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <ul class="clearfix protfolio-item" id="protfolio-msnry" style="position: relative; height: 864.765px;">

                <!-- Single Portfolio-->
                <?php foreach($orders as $order): ?>
                <li class="single-port-item category-talk" style="position: absolute; left: 0px; top: 0px;">
                  <a href="http://localhost/portofolio#portfolioModal" class="waves-effect waves-block waves-light modal-trigger" data-image-source="<?= $order['image'] ?>" data-title="<?= $order['name'] ?>" data-content="<?= $order['description'] ?>" data-demo-link=<?= $order['link'] ?>>
                    <div class="protfolio-image">
                      <img src="<?= $order['image'] ?>" alt="portfolio">
                      <div class="protfolio-content waves-effect waves-block waves-light">
                        <div class="protfolio-content__inner">
                          <h2 class="p-title"><?= $order['name'] ?></h2>
                        </div>
                      </div>
                      <div class="p-overlay"></div>
                    </div>
                  </a>
                </li>
                <?php endforeach ?>
              </ul>
              <!-- portfolio load more button-->
              <!--<a id="portfolio-item-loader" href="#" class="btn-floating btn-large waves-effect waves-light brand-bg"><i class="mdi-content-add"></i></a>-->
            </div>
          </div>
        </div>
      </div>
    </section>

  <script type="text/javascript" src="js/jquery.min.js"></script>
  <script src="js/jquery.easing.1.3.js"></script>
  <script src="js/detectmobilebrowser.js"></script>
  <script src="js/isotope.pkgd.min.js"></script>
  <script src="js/wow.min.js"></script>
  <script src="js/waypoints.js"></script>
  <script src="js/jquery.counterup.min.js"></script>
  <script src="js/jquery.nicescroll.min.js"></script>
  <script type="text/javascript" src="js/js"></script>
  <script src="js/gmaps.js"></script>
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/materialize.min.js"></script>
  <script src="js/jwplayer.js"></script>
  <script src="js/sweet-alert.min.js"></script>
  <script src="js/common(1).js"></script>
  <script src="js/main.js"></script>
  <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
  </body>

</html>
